### ISSUE TITLE
Doesn't work on My Robi App

### ISSUE THREAD

**Issue by shawanroy** [aniruddha-adhikary/shantofy#10]
**Doesn't work on My Robi App Notification.**

![image](https://user-images.githubusercontent.com/5551594/208860426-0d51d75d-a93a-4230-8ef4-b4cb3fa4ef10.png)

**Comment by aniruddha-adhikary** [comment]
Thanks for reporting this! I am marking this a good first issue so that newbie developers can come and help build this!

**Comment by aniruddha-adhikary** [comment]
https://play.google.com/store/apps/details?id=net.omobio.robisc&hl=en&gl=US

https://github.com/aniruddha-adhikary/shantofy/blob/main/app/src/main/java/net/adhikary/shantofy/core/TargetAppsProviderStatic.kt#L47
